name = input()
coust = input()
we = input()
cash = input()
y = int(int(cash) - int(we) * int(coust))

print("Чек")
print(f"<{name}> - <{we}>кг - <{coust}>руб/кг")
print(f"Итого: <{int(coust) *int(we)}>руб")
print(f"Внесено: <{cash}>руб")
print(f"Сдача: <{y}>руб")
